def err():
  raise(ValueException)

err()