try (try raise(RuntimeException) catch ValueException as e in 5) catch RuntimeException as e in 10